netty.conf:
  canalServerHost: 118.190.87.31:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  mode: tcp

context.conf:
  canalServerHost: 118.190.87.31:11111
  batchSize: 500
  syncBatchSize: 1000
  retries: 0
  timeout:
  accessKey:
  secretKey:
  mode: tcp

plugins.conf:
  instances:
      - name: redis
        properties:
          redis.pool.maxActive: 1024
          redis.pool.maxIdle: 200
          redis.pool.maxWait: 1000
          redis.pool.testOnBorrow: true
          redis.pool.testOnReturn: true
          redis.ip: 139.129.167.239
          redis.port: 6379
          redis.password: myredis
          redis.seconds: 10
      - name: mqtt
        properties:
          mqtt.broker: tcp://mqtt.izxcs.com:1883
          # mqtt.broker: tcp://127.0.0.1:1883
          mqtt.username: TEST
          mqtt.password: TEST
          mqtt.basetopicStart: public/smartPhone/
          mqtt.basetopicEnd: /info/
          mqtt.qos: 1
          mqtt.merchantIds: 1338
          mqtt.retries: 2

